version: 2.1
jobs:
  build:
    docker:
      - image: rust:latest
    steps:
      - checkout
      - run:
          name: Generate lockfile
          command: |
            cargo generate-lockfile
      - restore_cache:
          keys:
            - deps7-build-{{ checksum "Cargo.lock" }}
            - deps7-build
      - run:
          name: Build
          command: |
            cargo build --release
      - save_cache:
          key: deps7-build-{{ checksum "Cargo.lock" }}
          paths:
            - "target"
            - "~/.cargo"
  test:
    docker:
      - image: rust:latest
    steps:
      - checkout
      - run:
          name: Generate lockfile
          command: |
            cargo generate-lockfile
      - restore_cache:
          keys:
            - deps7-test-{{ checksum "Cargo.lock" }}
            - deps7-test
      - run:
          name: Test
          command: |
            cargo test
      - save_cache:
          key: deps7-test-{{ checksum "Cargo.lock" }}
          paths:
            - "target"
            - "~/.cargo"

workflows:
  version: 2
  build-test:
    jobs:
      - build
      - test
